/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.keyvault.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Management policy for a certificate.
 */
public class CertificatePolicy {
    /**
     * The certificate id.
     */
    @JsonProperty(value = "id", access = JsonProperty.Access.WRITE_ONLY)
    private String id;

    /**
     * Properties of the key backing a certificate.
     */
    @JsonProperty(value = "key_props")
    private KeyProperties keyProperties;

    /**
     * Properties of the secret backing a certificate.
     */
    @JsonProperty(value = "secret_props")
    private SecretProperties secretProperties;

    /**
     * Properties of the X509 component of a certificate.
     */
    @JsonProperty(value = "x509_props")
    private X509CertificateProperties x509CertificateProperties;

    /**
     * Actions that will be performed by Key Vault over the lifetime of a
     * certificate.
     */
    @JsonProperty(value = "lifetime_actions")
    private List<LifetimeAction> lifetimeActions;

    /**
     * Parameters for the issuer of the X509 component of a certificate.
     */
    @JsonProperty(value = "issuer")
    private IssuerParameters issuerParameters;

    /**
     * The certificate attributes.
     */
    @JsonProperty(value = "attributes")
    private CertificateAttributes attributes;

    /**
     * Get the certificate id.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Get properties of the key backing a certificate.
     *
     * @return the keyProperties value
     */
    public KeyProperties keyProperties() {
        return this.keyProperties;
    }

    /**
     * Set properties of the key backing a certificate.
     *
     * @param keyProperties the keyProperties value to set
     * @return the CertificatePolicy object itself.
     */
    public CertificatePolicy withKeyProperties(KeyProperties keyProperties) {
        this.keyProperties = keyProperties;
        return this;
    }

    /**
     * Get properties of the secret backing a certificate.
     *
     * @return the secretProperties value
     */
    public SecretProperties secretProperties() {
        return this.secretProperties;
    }

    /**
     * Set properties of the secret backing a certificate.
     *
     * @param secretProperties the secretProperties value to set
     * @return the CertificatePolicy object itself.
     */
    public CertificatePolicy withSecretProperties(SecretProperties secretProperties) {
        this.secretProperties = secretProperties;
        return this;
    }

    /**
     * Get properties of the X509 component of a certificate.
     *
     * @return the x509CertificateProperties value
     */
    public X509CertificateProperties x509CertificateProperties() {
        return this.x509CertificateProperties;
    }

    /**
     * Set properties of the X509 component of a certificate.
     *
     * @param x509CertificateProperties the x509CertificateProperties value to set
     * @return the CertificatePolicy object itself.
     */
    public CertificatePolicy withX509CertificateProperties(X509CertificateProperties x509CertificateProperties) {
        this.x509CertificateProperties = x509CertificateProperties;
        return this;
    }

    /**
     * Get actions that will be performed by Key Vault over the lifetime of a certificate.
     *
     * @return the lifetimeActions value
     */
    public List<LifetimeAction> lifetimeActions() {
        return this.lifetimeActions;
    }

    /**
     * Set actions that will be performed by Key Vault over the lifetime of a certificate.
     *
     * @param lifetimeActions the lifetimeActions value to set
     * @return the CertificatePolicy object itself.
     */
    public CertificatePolicy withLifetimeActions(List<LifetimeAction> lifetimeActions) {
        this.lifetimeActions = lifetimeActions;
        return this;
    }

    /**
     * Get parameters for the issuer of the X509 component of a certificate.
     *
     * @return the issuerParameters value
     */
    public IssuerParameters issuerParameters() {
        return this.issuerParameters;
    }

    /**
     * Set parameters for the issuer of the X509 component of a certificate.
     *
     * @param issuerParameters the issuerParameters value to set
     * @return the CertificatePolicy object itself.
     */
    public CertificatePolicy withIssuerParameters(IssuerParameters issuerParameters) {
        this.issuerParameters = issuerParameters;
        return this;
    }

    /**
     * Get the certificate attributes.
     *
     * @return the attributes value
     */
    public CertificateAttributes attributes() {
        return this.attributes;
    }

    /**
     * Set the certificate attributes.
     *
     * @param attributes the attributes value to set
     * @return the CertificatePolicy object itself.
     */
    public CertificatePolicy withAttributes(CertificateAttributes attributes) {
        this.attributes = attributes;
        return this;
    }

}
