/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.keyvault.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Parameters for the issuer of the X509 component of a certificate.
 */
public class IssuerParameters {
    /**
     * Name of the referenced issuer object or reserved names; for example,
     * 'Self' or 'Unknown'.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Type of certificate to be requested from the issuer provider.
     */
    @JsonProperty(value = "cty")
    private String certificateType;

    /**
     * Indicates if the certificates generated under this policy should be
     * published to certificate transparency logs.
     */
    @JsonProperty(value = "cert_transparency")
    private Boolean certificateTransparency;

    /**
     * The method the issuer will use to validate certificate creation and
     * renewal requests. Possible values include: 'email', 'dns-txt-token',
     * 'http-token'.
     */
    @JsonProperty(value = "validation_method")
    private ValidationMethod validationMethod;

    /**
     * A list of email addresses where validation emails should be sent for
     * specific DNS names.
     */
    @JsonProperty(value = "validation_emails")
    private List<ValidationEmail> validationEmails;

    /**
     * Get name of the referenced issuer object or reserved names; for example, 'Self' or 'Unknown'.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set name of the referenced issuer object or reserved names; for example, 'Self' or 'Unknown'.
     *
     * @param name the name value to set
     * @return the IssuerParameters object itself.
     */
    public IssuerParameters withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get type of certificate to be requested from the issuer provider.
     *
     * @return the certificateType value
     */
    public String certificateType() {
        return this.certificateType;
    }

    /**
     * Set type of certificate to be requested from the issuer provider.
     *
     * @param certificateType the certificateType value to set
     * @return the IssuerParameters object itself.
     */
    public IssuerParameters withCertificateType(String certificateType) {
        this.certificateType = certificateType;
        return this;
    }

    /**
     * Get indicates if the certificates generated under this policy should be published to certificate transparency logs.
     *
     * @return the certificateTransparency value
     */
    public Boolean certificateTransparency() {
        return this.certificateTransparency;
    }

    /**
     * Set indicates if the certificates generated under this policy should be published to certificate transparency logs.
     *
     * @param certificateTransparency the certificateTransparency value to set
     * @return the IssuerParameters object itself.
     */
    public IssuerParameters withCertificateTransparency(Boolean certificateTransparency) {
        this.certificateTransparency = certificateTransparency;
        return this;
    }

    /**
     * Get the method the issuer will use to validate certificate creation and renewal requests. Possible values include: 'email', 'dns-txt-token', 'http-token'.
     *
     * @return the validationMethod value
     */
    public ValidationMethod validationMethod() {
        return this.validationMethod;
    }

    /**
     * Set the method the issuer will use to validate certificate creation and renewal requests. Possible values include: 'email', 'dns-txt-token', 'http-token'.
     *
     * @param validationMethod the validationMethod value to set
     * @return the IssuerParameters object itself.
     */
    public IssuerParameters withValidationMethod(ValidationMethod validationMethod) {
        this.validationMethod = validationMethod;
        return this;
    }

    /**
     * Get a list of email addresses where validation emails should be sent for specific DNS names.
     *
     * @return the validationEmails value
     */
    public List<ValidationEmail> validationEmails() {
        return this.validationEmails;
    }

    /**
     * Set a list of email addresses where validation emails should be sent for specific DNS names.
     *
     * @param validationEmails the validationEmails value to set
     * @return the IssuerParameters object itself.
     */
    public IssuerParameters withValidationEmails(List<ValidationEmail> validationEmails) {
        this.validationEmails = validationEmails;
        return this;
    }

}
