/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.keyvault.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Details of the organization of the certificate issuer.
 */
public class OrganizationDetails {
    /**
     * Id of the organization.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Details of the organization administrator.
     */
    @JsonProperty(value = "admin_details")
    private List<AdministratorDetails> adminDetails;

    /**
     * Get id of the organization.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set id of the organization.
     *
     * @param id the id value to set
     * @return the OrganizationDetails object itself.
     */
    public OrganizationDetails withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get details of the organization administrator.
     *
     * @return the adminDetails value
     */
    public List<AdministratorDetails> adminDetails() {
        return this.adminDetails;
    }

    /**
     * Set details of the organization administrator.
     *
     * @param adminDetails the adminDetails value to set
     * @return the OrganizationDetails object itself.
     */
    public OrganizationDetails withAdminDetails(List<AdministratorDetails> adminDetails) {
        this.adminDetails = adminDetails;
        return this;
    }

}
