/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.keyvault.models;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for ValidationMethod.
 */
public final class ValidationMethod extends ExpandableStringEnum<ValidationMethod> {
    /** Static value email for ValidationMethod. */
    public static final ValidationMethod EMAIL = fromString("email");

    /** Static value dns-txt-token for ValidationMethod. */
    public static final ValidationMethod DNS_TXT_TOKEN = fromString("dns-txt-token");

    /** Static value http-token for ValidationMethod. */
    public static final ValidationMethod HTTP_TOKEN = fromString("http-token");

    /**
     * Creates or finds a ValidationMethod from its string representation.
     * @param name a name to look for
     * @return the corresponding ValidationMethod
     */
    @JsonCreator
    public static ValidationMethod fromString(String name) {
        return fromString(name, ValidationMethod.class);
    }

    /**
     * @return known ValidationMethod values
     */
    public static Collection<ValidationMethod> values() {
        return values(ValidationMethod.class);
    }
}
