/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.keyvault.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ValidationEmail model.
 */
public class ValidationEmail {
    /**
     * Validation emails will be sent for certificate requests with this dns
     * name as subject name or subject alternative name.
     */
    @JsonProperty(value = "dns")
    private String dnsName;

    /**
     * Email address where validation emails will be sent.
     */
    @JsonProperty(value = "email")
    private String email;

    /**
     * Get validation emails will be sent for certificate requests with this dns name as subject name or subject alternative name.
     *
     * @return the dnsName value
     */
    public String dnsName() {
        return this.dnsName;
    }

    /**
     * Set validation emails will be sent for certificate requests with this dns name as subject name or subject alternative name.
     *
     * @param dnsName the dnsName value to set
     * @return the ValidationEmail object itself.
     */
    public ValidationEmail withDnsName(String dnsName) {
        this.dnsName = dnsName;
        return this;
    }

    /**
     * Get email address where validation emails will be sent.
     *
     * @return the email value
     */
    public String email() {
        return this.email;
    }

    /**
     * Set email address where validation emails will be sent.
     *
     * @param email the email value to set
     * @return the ValidationEmail object itself.
     */
    public ValidationEmail withEmail(String email) {
        this.email = email;
        return this;
    }

}
